# Generated by Django 2.0.4 on 2018-04-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exalted', 'data_migration_001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exalted_type',
            name='exalted_type_id',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='rating',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_essence',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_exalted_subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Exalted.Exalted_subtype'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_exalted_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Exalted.Exalted_type'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_health_level_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Exalted.HealthLevelSet'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Exalted.Location'),
        ),
        migrations.AlterField(
            model_name='charm',
            name='charm_cost_motes',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charm',
            name='charm_cost_other',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='charm',
            name='charm_cost_wp',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charm',
            name='charm_duration',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='charm',
            name='charm_essence_min',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charm',
            name='charm_ex_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Exalted.Exalted_type'),
        ),
        migrations.AlterField(
            model_name='charm',
            name='charm_no_eclipse',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='charm',
            name='charm_prayer_strip',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='charm',
            name='charm_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Exalted.Charm_type'),
        ),
        migrations.AlterField(
            model_name='exalted_subtype',
            name='exalted_subtype_eclipse',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='exalted_subtype',
            name='exalted_subtype_exalted_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Exalted.Exalted_type'),
        ),
        migrations.AlterField(
            model_name='exalted_subtype',
            name='exalted_subtype_health_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Exalted.HealthLevels'),
        ),
        migrations.AlterField(
            model_name='exalted_subtype',
            name='exalted_subtype_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='exalted_type',
            name='exalted_type_ability_cost',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exalted_type',
            name='exalted_type_attribute_cost',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exalted_type',
            name='exalted_type_charm_cost',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exalted_type',
            name='exalted_type_essence_cost',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exalted_type',
            name='exalted_type_extended_charm_cost',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exalted_type',
            name='exalted_type_favored_cost',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exalted_type',
            name='exalted_type_favored_modifier',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exalted_type',
            name='exalted_type_favored_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Exalted.FavoredItems'),
        ),
        migrations.AlterField(
            model_name='exalted_type',
            name='exalted_type_health_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Exalted.HealthLevels'),
        ),
    ]
