# Generated by Django 2.0.4 on 2018-04-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exalted', '0001_auto_20180420_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charm',
            name='charm_abilitySet',
        ),
        migrations.AddField(
            model_name='charm',
            name='charm_abilitySet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Exalted.AbilitySet'),
        ),
    ]
