# Generated by Django 2.0.4 on 2018-04-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exalted', '0002_auto_20180420_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charm',
            name='charm_abilitySet',
        ),
        migrations.AddField(
            model_name='abilityset',
            name='charm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Exalted.Charm'),
            preserve_default=False,
        ),
    ]
