# Generated by Django 2.0.4 on 2018-04-20 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exalted', '0003_auto_20180420_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='charm_after',
            field=models.ManyToManyField(null=True, related_name='_charm_charm_after_+', to='Exalted.Charm'),
        ),
        migrations.AddField(
            model_name='charm',
            name='charm_before',
            field=models.ManyToManyField(null=True, related_name='_charm_charm_before_+', to='Exalted.Charm'),
        ),
        migrations.AlterField(
            model_name='abilityset',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abilityset', to='Exalted.Ability'),
        ),
        migrations.AlterField(
            model_name='abilityset',
            name='charm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abilityset', to='Exalted.Charm'),
        ),
    ]
