# Generated by Django 2.0.4 on 2018-04-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exalted', '0004_auto_20180421_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charm',
            name='charm_after',
            field=models.ManyToManyField(related_name='_charm_charm_after_+', to='Exalted.Charm'),
        ),
        migrations.AlterField(
            model_name='charm',
            name='charm_before',
            field=models.ManyToManyField(related_name='_charm_charm_before_+', to='Exalted.Charm'),
        ),
    ]
