# Generated by Django 2.0.4 on 2018-04-21 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Exalted', '0005_auto_20180421_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='AbilitySet',
            new_name='RequirementSet',
        ),
        migrations.RenameModel(
            old_name='Ability',
            new_name='Requirement',
        ),
        migrations.AddField(
            model_name='charm',
            name='charm_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charm',
            name='charm_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requirementset',
            name = 'ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abilityset',
                                        to='Exalted.Requirement'
            ),
        ),



    ]
