# Generated by Django 2.0.4 on 2018-04-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exalted', '0006_auto_20180421_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementset',
            name='ability',
        ),
        migrations.AddField(
            model_name='charm',
            name='charm_tags',
            field=models.ManyToManyField(related_name='charm', to='Exalted.Tag'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Requirement', to='Exalted.RequirementType'),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirementset', to='Exalted.Requirement'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag', to='Exalted.Tag_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirementset',
            name='charm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirementset', to='Exalted.Charm'),
        ),
    ]
