# Generated by Django 2.0.4 on 2018-04-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exalted', '0009_auto_20180421_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charm',
            name='charm_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct', to='Exalted.Charm_type'),
        ),
    ]
